title: The PDF of Naval Ravikant
description: Like *The Almanack*, but edited. And organized.
theme: just-the-docs

url: https://scottsemple.github.io/the-pdf-of-naval-ravikant

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
